# Generated by Django 4.2.7 on 2024-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_gr",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("AB", "Ab"), ("O", "O"), ("DOB", "Dob"), ("AB+", "Ab Plus")],
                default=None,
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="images/profile/"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=None, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(default=None, null=True),
        ),
    ]
