# Generated by Django 4.2.7 on 2024-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_price_address_productrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=1, upload_to="images/shop/"),
            preserve_default=False,
        ),
    ]
